flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField, TextAreaField
from wtforms.validators import DataRequired


class NewPostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    body = TextAreaField('Body', validators=[DataRequired()])
    submit = SubmitField('Post')

flaskblog/main/routes.py
from flask import request, Blueprint, render_template, current_app
from flaskblog.models import Post



main = Blueprint('main', __name__)

@main.route('/')
@main.route('/home')
def home():
    page = request.args.get('page', 1, type=int)
    
    posts = Post.query.order_by(Post.created_at.desc()).paginate(page=page,per_page=current_app.config['POST_PER_PAGE'])

    return render_template('home.html', posts = posts, title='learning flask')

@main.route('/about')
def about_us():

    return render_template('about.html')

flaskblog/posts/routes.py
from flask_login.utils import  current_user,  login_required
from flask import request, abort,Blueprint,render_template, url_for, flash, redirect
from flaskblog.models import  Post
from flaskblog import  db
from flaskblog.posts.forms import NewPostForm



posts = Blueprint('posts', __name__)


@posts.route('/post/new', methods = ['GET', 'POST'])
@login_required
def new_post():
    form = NewPostForm()
    legend = 'New Post'
    if form.validate_on_submit():
        
        post = Post(title = form.title.data, content=form.body.data, author= current_user)
        db.session.add(post)
        db.session.commit()
        flash('post created succesfully', 'succes')
        return redirect(url_for('main.home'))
    return render_template('new_post.html', title='New Post', form=form)

@posts.route('/post/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route('/post/<int:post_id>/update', methods = ['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    legend = 'Edit Post'
    if post.author != current_user:
        abort(403)
    form = NewPostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.body.data
        db.session.commit()
        flash('your post has been update', 'success')
        return redirect(url_for('posts.post', post_id = post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.body.data = post.content
    
    return render_template('new_post.html', title=post.title, post=post, form=form, legend=legend)


@posts.route('/post/<int:post_id>/delete', methods = ['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('post has been deleted succesfully', 'info')
    return redirect(url_for('main.home'))

flaskblog/users/routes.py
from flask import Blueprint,request, abort, render_template, url_for, flash, redirect, current_app
from flask_login.utils import login_user, current_user, logout_user, login_required
from flaskblog.users.utils import delete_profile_picture, save_picture, send_reset_email
from flaskblog.models import User, Post
from flaskblog import  db, bcrypt, mail
from flaskblog.users.forms import (LoginForm, RegistrationForm, RequestResetForm, 
                                UpdateAccountForm, RequestResetForm, ResetPasswordForm)


users = Blueprint('users', __name__)

@users.route('/register',methods = ['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect( url_for('main.home'))

    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username = form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Account created for {form.username.data} ! you can now log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form, title = 'Register')

@users.route('/login', methods = ['POST', 'GET'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by( email = form.email.data).first()
        if user  and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            flash('you have been logged in', 'success')
            return redirect(url_for('main.home'))
        else:
            flash('login unsuccessful please check email and password', 'danger')
    return render_template('login.html', form=form, title = 'Login')

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route('/account', methods = ['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    
    if form.validate_on_submit():
        if form.picture.data:
            old_profile_pic = current_user.profile_pic 
            picture_file = save_picture(form.picture.data)

            if old_profile_pic == 'default.jpg':
                pass
            else:
                delete_profile_picture(old_profile_pic)
            
            current_user.profile_pic = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User Info updated succesfully', 'info')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    
        
    profile_pic = url_for('static',filename='profile_pics/' + current_user.profile_pic)
    return render_template('account.html', title = 'Account details', form=form,profile_pic=profile_pic)



@users.route('/posts/<string:username>')
def posts_by_user(username):
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page',1, type=int)
 
    posts = Post.query.filter_by(author=user)\
                    .order_by(Post.created_at.desc())\
                    .paginate(page=page,per_page=current_app.config['POST_PER_PAGE'])
    return render_template('user_posts.html', title=f'Posts by {user.username}', posts=posts, user=user)


@users.route('/resetpassword', methods = ['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = RequestResetForm()
    
    if form.validate_on_submit():
       
        user = User.query.filter_by(email=form.email.data).first()
        
        # send_reset_email(user) will work on this functionality latter
        flash('An email has been sent with instructions to reset your password', 'success')
        return redirect(url_for('users.login'))
    return render_template('request_reset.html', title='Reset Password', form=form)


@users.route('/resetpassword/<string:token>', methods=['GET','POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    user = User.verify_reset_token(token)
    if user is None:
        flash('invalid token or expired token', 'warning')
        return redirect(url_for('users.reset_request'))

    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your account password has been updated! You can now log in with your new password', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_password.html', form=form, title='Reset Password')
    

flaskblog/templates/about.html
{% extends "layout.html" %} 
{% block content %}
    <h2>about us </h2>

{% endblock content%}

flaskblog/templates/account.html
{% extends "layout.html" %} 
{% block content %}
    <div class="contect-section">
        <div class="media">
            <img  class="rounded-circle account-img" src="{{ profile_pic }}"/>
            <div class="media-body">
                <h2 class="account-heading"> {{ current_user.username }}</h2>
                <p class="text-secondary"> {{ current_user.email }} </p>
            </div>

        </div>

    </div>

    <form method="POST" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4"> Update Account Info </legend>
            <div class="form-group">
                
                {{form.username.label(class="form-control-label")}}
                {% if form.username.errors %}
                    {{ form.username(class="form-control form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                            <span> {{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{form.username(class="form-control form-control-lg")}} 
                {%  endif %}
                
            </div>

            <div class="form-group">
                {{form.email.label(class="form-control-label")}}
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span> {{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{form.email(class="form-control form-control-lg")}} 
                {%  endif %}
            </div>

            <div class="form-group mt-3">
                {{form.picture.label()}} <br />
                {{ form.picture(class='form-control-file') }}
                {% if form.picture.errors %}
                    {% for error in form.picture.errors %}
                    <span class="text-danger"> {{ error }}</span><br />
                    {% endfor %}
                {% endif %}
            </div>

        </fieldset>

        <div class="form-group">
            {{form.submit(class="btn btn-outline-info mt-3")}}
           
        </div>
    </form>
{% endblock content %}

flaskblog/templates/home.html
{% extends "layout.html" %} 
{% block content %}
    {% for post in posts.items %}
        <div class="blog-post">
            <h1> <a class="article-title" href="{{ url_for('posts.post', post_id=post.id)}}">{{ post.title }}</a> </h1>
            <p> by <a href="{{url_for('users.posts_by_user', username=post.author.username)}}">{{ post.author.username }}</a> on {{ post.created_at.strftime('%Y-%m-%d') }}</p>
            <p> {{ post.content }} </p>
        </div>    
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if posts.page == page_num %}
                <a class="btn btn--info mb-4" href="{{ url_for('main.home', page=page_num)}}"> {{page_num}} </a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num)}}"> {{page_num}} </a>
            {% endif %}   
        {% else %}
            ....
        {% endif %}
         
    {% endfor %}
{% endblock content %}

flaskblog/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link href="{{ url_for('static', filename='custom.css')}}" type="text/css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Flask blog </title>
    {% endif %}
  
</head>

<body>
    
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{{url_for('main.home')}}">Flask Blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <li class="nav-item active">
                  <a class="nav-link" href="{{url_for('main.home')}}">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{url_for('main.about_us')}}">About</a>
                </li>
                {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('users.logout')}}">Logout</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('users.account')}}">Account</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('posts.new_post')}}">New Post</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                      <a class="nav-link" href="{{url_for('users.login')}}">Login</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{{url_for('users.register')}}">Register</a>
                    </li>
                {%  endif %}
                
              </ul>
            </div>
          </nav>
        <div class="row">
            <div class="col-md-9">
                {% with messages = get_flashed_messages(with_categories = true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {%  endif %}
                {% endwith %}
                {% block content %} {% endblock %}
            </div>

            <div class="col-md-3">
                <div  class="sidebar">
                    <h2>Our side Bar</h2>
                    <p>this is a sample side bar</p>
                    <a href="#" class="btn btn-secondary btn-sm" role="button" aria-pressed="true">Latest posts</a>
                    <a href="#" class="btn btn-secondary btn-sm" role="button" aria-pressed="true">Latest posts</a>
                    <a href="#" class="btn btn-secondary btn-sm" role="button" aria-pressed="true">Latest posts</a>
                    <a href="#" class="btn btn-secondary btn-sm" role="button" aria-pressed="true">Latest posts</a>
                </div>
            </div>

        </div>
    </div>

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>

</body>
</html>

flaskblog/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <form method="POST">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4"> Join today </legend>
            

            <div class="form-group">
                {{form.email.label(class="form-control-label")}}
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is_invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span> {{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{form.email(class="form-control form-control-lg")}} 
                {%  endif %}
            </div>

            <div class="form-group">
                {{form.password.label(class="form-control-label")}}
                {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is_invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span> {{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{form.password(class="form-control form-control-lg")}} 
                {%  endif %}
            </div>

            <div class="form-check">
                {{ form.remember(class="form-check-input")}}
                {{ form.remember.label(class="form-check-label")}}
            </div>


        </fieldset>

        <div class="form-group">
            {{form.submit(class="btn btn-outline-info mt-3")}}
        </div>
        <small class="text-muted ml-2">
            <a href="{{url_for('users.reset_request')}}"> Forgot Password ?</a>

        </small>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            Dont have an account ?  <a class="ml-2" href="{{ url_for('users.register') }}" > Sign Up now</a>
        </small>
    </div>
{% endblock %}

flaskblog/templates/new_post.html
{% extends "layout.html" %}
{% block content %}
    <form method="POST">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4"> {{ legend }} </legend>
            

            <div class="form-group">
                {{form.title.label(class="form-control-label")}}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is_invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span> {{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{form.title(class="form-control form-control-lg")}} 
                {%  endif %}
            </div>

            <div class="form-group">
                {{form.body.label(class="form-control-label")}}
                {% if form.body.errors %}
                    {{ form.body(class="form-control form-control-lg is_invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.body.errors %}
                            <span> {{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{form.body(class="form-control form-control-lg")}} 
                {%  endif %}
            </div>

        </fieldset>

        <div class="form-group">
            {{form.submit(class="btn btn-outline-info mt-3")}}
        </div>
        
    </form>
    
{% endblock %}

flaskblog/templates/post.html
{% extends "layout.html" %} 
{% block content %}
    <div>
        <h1>{{ post.title }}</h1>
        <p> {{ post.content }}</p>
        <p> {{ post.author.username}}</p>
        {% if current_user == post.author%}
        <div >
            <a class="btn btn-secondary btm-sm m-1" href="{{url_for('posts.update_post', post_id=post.id)}}" > Edit </a>
            <form action="{{url_for('posts.delete_post', post_id=post.id)}}" method="POST">
              <input type="submit" value="Delete" class="btn btn-danger" />
            </form>
            
        </div>
        {% endif %}
    </div>
   

{% endblock content%}

flaskblog/templates/register.html
{% extends "layout.html" %}
{% block content %}
    <form method="POST">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4"> Join today </legend>
            <div class="form-group">
                
                {{form.username.label(class="form-control-label")}}
                {% if form.username.errors %}
                    {{ form.username(class="form-control form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                            <span> {{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{form.username(class="form-control form-control-lg")}} 
                {%  endif %}
                
            </div>

            <div class="form-group">
                {{form.email.label(class="form-control-label")}}
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span> {{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{form.email(class="form-control form-control-lg")}} 
                {%  endif %}
            </div>

            <div class="form-group">
                {{form.password.label(class="form-control-label")}}
                {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span> {{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{form.password(class="form-control form-control-lg")}} 
                {%  endif %}
            </div>

            <div class="form-group">
                {{form.confirm_password.label(class="form-control-label")}}
                {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class="form-control form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.confirm_password.errors %}
                            <span> {{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{form.confirm_password(class="form-control form-control-lg")}} 
                {%  endif %}
            </div>

        </fieldset>

        <div class="form-group">
            {{form.submit(class="btn btn-outline-info mt-3")}}
           
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already have an account ?  <a class="ml-2" href="{{ url_for('login') }}" > Sign In</a>
        </small>
    </div>
{% endblock %}

flaskblog/templates/request_reset.html
{% extends "layout.html" %} 
{% block content %}
<form method="POST">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4"> Request For Password Reset </legend>
        

        <div class="form-group">
            {{form.email.label(class="form-control-label")}}
            {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                        <span> {{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{form.email(class="form-control form-control-lg")}} 
            {%  endif %}
        </div>
    </fieldset>

    <div class="form-group">
        {{form.submit(class="btn btn-outline-info mt-3")}}
       
    </div>
</form>

{% endblock content%}

flaskblog/templates/reset_password.html
{% extends "layout.html" %}
{% block content %}
    <form method="POST">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4"> Reset Password </legend>
            

            <div class="form-group">
                {{form.password.label(class="form-control-label")}}
                {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span> {{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{form.password(class="form-control form-control-lg")}} 
                {%  endif %}
            </div>

            <div class="form-group">
                {{form.confirm_password.label(class="form-control-label")}}
                {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class="form-control form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.confirm_password.errors %}
                            <span> {{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{form.confirm_password(class="form-control form-control-lg")}} 
                {%  endif %}
            </div>

        </fieldset>

        <div class="form-group">
            {{form.submit(class="btn btn-outline-info mt-3")}}
           
        </div>
    </form>
{% endblock %}

flaskblog/templates/user_posts.html
{% extends "layout.html" %} 
{% block content %}
    <h1 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h1>
    {% for post in posts.items %}
        <div class="blog-post">
            <h1> <a class="article-title" href="{{ url_for('posts.post', post_id=post.id)}}">{{ post.title }}</a> </h1>
            <p> by <a href="{{url_for('users.posts_by_user', username=post.author.username)}}">{{ post.author.username }}</a> on {{ post.created_at.strftime('%Y-%m-%d') }}</p>
            <p> {{ post.content }} </p>
        </div>    
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if posts.page == page_num %}
                <a class="btn btn--info mb-4" href="{{ url_for('users.posts_by_user', username=user.username, page=page_num)}}"> {{page_num}} </a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('users.posts_by_user', username=user.username,page=page_num)}}"> {{page_num}} </a>
            {% endif %}   
        {% else %}
            ....
        {% endif %}
         
    {% endfor %}
{% endblock content %}